// This is first and secound  task of JavaScript
let helloJs = ("Hello JavaScript");
console.log(helloJs);
let myName = ("My name is Shakib");
console.log(myName);
let myAim = ("I am excited to become a web developer");
console.log(myAim);
let number1 = 25;
let number2 = 10;
console.log("Addition of two numbers is: " + (number1 + number2));
console.log("Subtraction of two numbers is: " +(number1 - number2));
console.log("Multiplication of two numbers is: " + (number1 * number2));
console.log("Division of two numbers is: " + (number1 / number2));
console.log("Modulus of two numbers is: " + (number1 % number2));
// This is third task of javaScript
let studentName = "Shakib";
let studentAge = 25;
let studentAddress = "Dhaka, Bangladesh";
let isStudent = true;
console.log("Student Name: " , studentName);
console.log("Student Age: " , studentAge);
console.log("Student Address: " , studentAddress);
console.log("Is Student: " , isStudent);
// This is fourth task of javaScript
let a =100;
let b = "Programming";
let c = true;
let d = false;
let e = 3.1416;
console.log("a:", typeof a);
console.log("b:", typeof b);
console.log("c:", typeof c);
console.log("d:", typeof d);
console.log("e:", typeof e);
// This is eighth task of javaScript
let score =50;
score += 10;
console.log("Score after addition +=10:", score);
score -= 5;
console.log("Score after subtraction -=5:", score);
score *= 2;
console.log("Score after multiplication *=2:", score);
score /= 5;
console.log("Score after division /=5:", score);
score %= 4;
console.log("Score after modulus %=4:", score);
let price = 200;
let quantity = 3;
let discount =10;
let totalPrice = price*quantity;
let discountPrice = (totalPrice*discount)/100;
let finalPrice = totalPrice - discountPrice;
console.log("Total Price: " , totalPrice);
console.log("Discount Price: " , discountPrice);
console.log("Final Price after discount: " , finalPrice);
// This is mini project- Personal Introduction Card
let fullName = "Md. Tanvir Jahan Shakib";
let age= 23;
let country = "Bangladesh";
let favoriteLanguage = "JavaScript";
let dreamJob = "Web Developer";
let yearToGoal = 1;
let isLearningJavaScript = true;
console.log("=================================");
console.log("Personal Introduction Card");
console.log("=================================");
console.log("Full Name:", fullName);
console.log("Age:", age);
console.log("Country:", country);
console.log("Favorite Programming Language:", favoriteLanguage);
console.log("Dream Job:", dreamJob);
console.log("Years to Achieve Goal:", yearToGoal);
console.log("Is Learning JavaScript:", isLearningJavaScript);
console.log("=================================");